### ISSUE TITLE
`caiman_loader.py` uses skimage but `skimage` is not listed in the `requirements.txt`.

### ISSUE THREAD

**Issue by tdincer** [datajoint/element-interface#20]

**Comment by kabilar** [comment]
Thanks @tdincer.  CaImAn dependencies can be installed using the `extras_require` feature in setup.py (see [line 40](https://github.com/datajoint/element-interface/blob/23bb10aa43cc7cac0c0958c4e55eed10e85b7aee/setup.py#L40)).
