### ISSUE TITLE
Revisit numpy version lock

### ISSUE THREAD

**Issue by CBroz1** [datajoint/element-interface#27]
I ran into issues installing pynwb requirements with an exact version of numpy. Do we have documentation as to why exactly this version of numpy?

**Comment by kabilar** [comment]
I believe numpy==1.21.0 is a Suite2p requirement.

**Comment by tdincer** [comment]
I'm using `pynwb=1.4.0` with `numpy=1.21.0`.

**Comment by CBroz1** [comment]
It looks like [Suite2p](https://github.com/MouseLand/suite2p/blob/main/setup.py) asks for `numpy>=1.16`. I propose changing to `=>1.20`

Perhaps related to `pynwb==2.0` on my end @tdincer: specifically, nwb-conversion-tools 0.11.0 requires `numpy>=1.21.0`

**Comment by kabilar** [comment]
Hi @CBroz1,

The following seems to work for me.

```
conda create -n test_env_20220317 python=3.8.11
conda activate test_env_20220317
pip install git+https://github.com/datajoint-company/suite2p.git
pip install pynwb
pip install git+https://github.com/catalystneuro/nwb-conversion-tools.git

import numpy
import pynwb
import nwb_conversion_tools
```

Resulting package versions
- numpy - 1.21.5 (Have also tried with numpy==1.21.0)
- pynwb - 2.0.1
- nwb-conversion-tools - 0.11.3

**Comment by CBroz1** [comment]
Worked for me too on a fresh environment
- suite2p 0.10.4.dev8+gbc85d6d
- numpy 1.21.5
- pynwb 2.0.1
- nwb_conversion_tools 0.11.3
- dandi 0.36.0
- deeplabcut 2.2.0.6 - previously caused issues

I'll plan to test `workflow-calcium-imaging` with `numpy>=1.20` after our current sprint

**Comment by CBroz1** [comment]
This is now causing issues for a user who wants to use both `element-calcium-imaging` and `element-deeplabcut`. I will investigate the use of `element-deeplabcut` with `numpy>=1.21`

**Comment by CBroz1** [comment]
Everything ran smoothly when I removed the `numpy=1.20` requirement from `element-deeplabcut`

**Comment by JaerongA** [comment]
Maybe a related issue so I reopen the discussion here. 

Here's the error I got while installing the package with the latest python version (3.10.4)

>   × Building wheel for numpy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [207 lines of output]
      setup.py:63: RuntimeWarning: NumPy 1.21.0 may not yet support Python 3.10.

Either bumping up numpy to `numpy==1.22.1` in requirements.txt or installing `python<3.10` resolved the issue.

**Comment by CBroz1** [comment]
@kabilar - What approach should the elements take to python `3.10`? It's supported by DataJoint Core, but incompatible with numpy `1.21`. 

If it's not [suite2p requirements](https://github.com/MouseLand/suite2p/blame/main/setup.py) that motivate pinning on our end, perhaps there's another dependency?

**Comment by CBroz1** [comment]
@kabilar - Does our removal of `extras_require` change our need to numpy pin?

**Comment by CBroz1** [comment]
An additional note: in my M1 installation Element DeepLabCut, I hit the following dependency conflict
- Element DeepLabCut -> DeepLabCut==2.2.2 -> Tensorflow-MacOS~=2.10 -> numpy≥1.23
- Element DeepLabCut -> Element Interface -> numpy==1.21

**Comment by CBroz1** [comment]
Hi @tdincer - I had trouble getting CaImAn running on my M1 with numpy~=1.21, but issues seem resolve after updating to 1.24. Have you had that issue?

**Comment by tdincer** [comment]
> Hi @tdincer - I had trouble getting CaImAn running on my M1 with numpy~=1.21, but issues seem resolve after updating to 1.24. Have you had that issue?

@CBroz1 I'll resolve all caiman related issues this month. Looks like we won't have caiman and suite2p together in a workflow. This will allow us to relax the numpy version constraint.

**Comment by kabilar** [comment]
@CBroz1 @tdincer @JaerongA Now that the numpy version pin is removed (#63), is this issue resolved?

**Comment by kabilar** [comment]
Chris, we should support python 3.10.  Since the numpy version pin is removed, I will close this issue, but please let me know if the dependency conflicts arise again.  Thank you.
