### ISSUE TITLE
Revise `utils.ingest_csv_to_table` to permit embedded lists

### ISSUE THREAD

**Issue by CBroz1** [datajoint/element-interface#36]
Currently, this function is a general solve for ingesting data from CSVs. If a CSV feeds multiple tables, the same path must be provided for each table. For a cleaner approach, tables could be provided as embedded lists.

**Comment by kabilar** [comment]
Thanks @CBroz1.  Also, `ingest_general` uses commas as a delimiter, however this causes issues when parsing strings with commas (e.g. session.SessionNote).  So we should figure out an alternative strategy.

**Comment by CBroz1** [comment]
Following feedback on [this PR](https://github.com/datajoint/element-interface/pull/66), a [datajoint-python](https://github.com/datajoint/datajoint-python/pull/1067) PR added the ability for direct CSV insertion. This migrates looping to the insert context. e.g.
```python
my_path=pathlib.Path('my.csv')
for table in [Table1, Table2]:
  table.insert(my_path)
```
