### ISSUE TITLE
Publish initial release of Elements on PyPI

### ISSUE THREAD

**Issue by kabilar** [datajoint/element-interface#45]
- [x] element-lab
- [x] element-animal
- [x] element-session
- [x] element-event
- [x] element-array-ephys
- [x] element-calcium-imaging
- [x] element-miniscope
- [x] element-deeplabcut
- [x] element-facemap
- [x] element-electrode-localization

**Comment by CBroz1** [comment]
PRs to add the CICD that will trigger release
- [element-event PR 26](https://github.com/datajoint/element-event/pull/26)
- [element-electrode-localization PR 16](https://github.com/datajoint/element-electrode-localization/pull/16)
- [element-miniscope PR 29](https://github.com/datajoint/element-miniscope/pull/29)
- [element-facemap PR 16](https://github.com/datajoint/element-facemap/pull/16)

**Comment by kabilar** [comment]
Thanks @CBroz1!
