### ISSUE TITLE
`black` formatting across elements

### ISSUE THREAD

**Issue by CBroz1** [datajoint/element-interface#48]
Our internal meeting on May 4th will, in part, cover [black](https://github.com/psf/black) and recommendations for strategizing conversion. 

`black` pull requests merged
- [x] element-lab
- [x] element-animal
- [x] element-session
- [x] element-event
- [x] element-deeplabcut
- [x] element-facemap
- [x] element-miniscope
- [x] element-electrode-localization
- [x] element-calcium-imaging
- [x] workflow-session
- [x] workflow-calcium-imaging
- [x] workflow-array-ephys
- [x] workflow-deeplabcut
- [x] element-interface
- [ ] element-optogenetics 
- [ ] workflow-miniscope
- [ ] workflow-facemap

Outstanding pull requests so `black` on hold
- [ ] element-array-ephys

N/A
- element-visual-stimulus
- workflow-visual-stimulus

**Comment by kabilar** [comment]
Issue transfer from datajoint-elements is stuck:
```
This issue is being transferred. Timeline may not be complete until it finishes.
```
