### ISSUE TITLE
Install.md: Additional `graphviz` installation steps for `dj.Diagram()` 

### ISSUE THREAD

**Issue by CBroz1** [datajoint/element-interface#50]
Following the notebooks, I encountered errors when generating diagrams. Specifically, I saw the following:

```
FileNotFoundError: [Errno 2] "dot" not found in path.
```

[Comments elsewhere](https://github.com/WillKoehrsen/Data-Analysis/issues/36#issuecomment-498710710) indicate that `graphviz` needs to be installed system-wide (e.g., `brew install graphviz`) rather than installed via `pip`. Installing with `brew` fixed the issue in my case. 

Should this be noted in documentation? Should dependency lists be refined elsewhere?

**Comment by sidml** [comment]
This fixes the issue
`sudo apt install python-pydot python-pydot-ng graphviz`
[ref](https://github.com/WillKoehrsen/Data-Analysis/issues/36#issuecomment-498710710)

**Comment by CBroz1** [comment]
Documentation on this topic will either be covered by the [datajoint python documentation](https://datajoint.com/docs/core/datajoint-python/)
