### ISSUE TITLE
Rename this repository

### ISSUE THREAD

**Issue by kabilar** [datajoint/element-interface#6]
Hi team, for `element_data_loader`, I propose a name change to `element_interface`.  This package will have functions that are used by multiple `elements` and possibly by other projects.  This repository will serve the following purposes:

1. Load datasets from packages (`caiman_loader`, `kilosort_loader`, etc.)
2. Trigger packages (`suite2p_trigger`, etc.)
3. Functions that are used commonly amongst the elements (`dict_to_uuid`, `find_full_path`, etc.)

Please let me know your thoughts.  Thanks.

**Comment by kabilar** [comment]
Hi @datajoint/elements team, I propose this name change by January 10, 2022.  Please let me know your thoughts.  Thank you.

**Comment by CBroz1** [comment]
Sure, we can plan for many minor edits to co-occur across elements. Because we'll be editing across elements, I propose renaming to [element-animal -> element-subject](https://github.com/datajoint/element-animal/issues/15) simultaneously.

**Comment by kabilar** [comment]
Thanks @CBroz1.  I will make the updates today for `element-data-loader` to `element-interface` and `element-animal` to `element-subject`, and will submit for your review.  Then we can rename the repositories on GitHub.
