### ISSUE TITLE
Multiple z devices (PrairieView metadata reader)

### ISSUE THREAD

**Issue by juremaj** [datajoint/element-interface#77]
I've been trying to set up datajoint for a calcium imaging pipeline and I ran into issues importing PrairieView metadata from the .xml file. Essentially I get an assertion error, from `prairieviewreader.py`/`get_pv_metadata` (part of `element_interface`) because `z_fields.size == n_depths`. I think the issue is that our microscope is using 2 different devices for adjusting Z (`Z Focus` and `Optotune ETL 10-30`), but `prairieviewreader.py` hardcodes the zeroth index as the preferred z device (see below - [@subindex='0']):

![image](https://user-images.githubusercontent.com/53050061/220633957-da6982e2-4034-455d-a131-71ce0fbaaf0e.png)

But since I have two devices, this restricts the reading to only the first one. Heres what my metadata (.xml) looks like:

![image](https://user-images.githubusercontent.com/53050061/220632911-41e271c1-5191-4f71-8817-01c91c91832b.png)

In my data the other device was used (`Optotune ETL 10-30`, index=1) and the .xml logs this under 'zDevice':

![image](https://user-images.githubusercontent.com/53050061/220634116-ab47e0a3-d46e-4d7d-941c-415f1371a80a.png)

For now I just did a hacky fix of hardcoding `[@subindex='1']` instead of 0, since all my data is using the second device. I am not sure how many people are using a second z device, but I was thinking it could be good to add the handling of this specific case.

**Comment by kushalbakshi** [comment]
Hi @juremaj, we haven't come across instances where the PrairieView system uses multiple z-devices. At this time, implementing this feature is not on our roadmap but we welcome community contributions. Our documentation provides [contribution guidelines](https://datajoint.com/docs/community/contribute/) if you want to explore that option.

**Comment by kabilar** [comment]
Thanks for the report, @juremaj.  Would you be able to send us an example dataset so that we can scope out the issue?  If so, feel free to email me the data at kabilar@datajoint.com.

**Comment by juremaj** [comment]
Hi @kabilar! Thanks for the reply. I sent you the example metadata (the same as the one in the screenshots above). Running  `element_interface.prairieviewreader.get_pv_metadata()` on that file should replicate the issue.

**Comment by kabilar** [comment]
Thank you, @juremaj.  We are looking into the issue and exploring possible solutions.

**Comment by kushalbakshi** [comment]
Hi @juremaj we've determined the issue - the `.xml` settings files vary significantly amongst users for indicating `ZAxis`. Based on the examples we have, we will develop a more adaptable solution that will work for you as well as others. This fix will be implemented shortly.

**Comment by kabilar** [comment]
@juremaj, PyPI releases for [element-interface 0.5.1](https://pypi.org/project/element-interface/#history) and [element-calcium-imaging 0.5.5](https://pypi.org/project/element-calcium-imaging/#history) have been made to address this issue.  Please let us know if you run into any further issues.  Thank you.
