### ISSUE TITLE
Clean up variable names in `prairieviewreader.py`

### ISSUE THREAD

**Issue by kushalbakshi** [datajoint/element-interface#79]
### Problem

The `prairieviewreader.py` file contains a function to read data from Bruker's PrairieView system for acquiring calcium imaging data. The function parses through an `.xml` metadata and settings file with the goal of populating DataJoint's `ScanInfo` table in `element-calcium-imaging`. The variable names within this function could be adapted to improve readability for contributors and future developers. 

### Requirements

Variable names should be descriptive and ensure that contributors external to DataJoint are able to contribute changes and bug fixes with ease. 

### Justification

This feature will ensure future developers and contributors are able to focus on developing the code rather than attempting to understand what is being accomplished by each of the steps in the function. 

### Alternative Considerations

Use comments to guide the user where changing the variable names doesn't make sense or help improve readability of the code.

**Comment by kabilar** [comment]
Fixed in #86.
